CREATE TABLE [dbo].[Paper_Para_Abnormal] (
[ID] int NOT NULL IDENTITY(1,1) ,
[reel_code] char(10) NULL ,
[prod_id] int NULL ,
[machine_id] int NULL ,
[rec_date] datetime NULL  ,
[oper_id] int NULL ,
[temperature] float NULL ,
[humidity] float NULL ,
[director_name] char(10) NULL ,
[remark] char(100) NULL,
[sur_oil_imbibition_f] float NULL ,
[sur_oil_imbibition_b] float NULL ,
[water_imbibition_f] float NULL ,
[water_imbibition_b] float NULL ,
[sur_Strength_v_f] float NULL ,
[sur_Strength_v_b] float NULL ,
[sur_Strength_h_f] float NULL ,
[sur_Strength_h_b] float NULL ,
[oil_perme_f] float NULL ,
[oil_perme_f_lv] float NULL ,
[oil_perme_b] float NULL ,
[oil_perme_b_lv] float NULL ,
[roughness_v_f] float NULL ,
[roughness_v_b] float NULL ,
[roughness_h_f] float NULL ,
[roughness_h_b] float NULL ,
[perme_v_f] float NULL ,
[perme_v_b] float NULL ,
[perme_h_f] float NULL ,
[perme_h_b] float NULL ,
[burst_f] float NULL ,
[burst_b] float NULL ,
[evennessIdx_f] float NULL ,
[evennessIdx_b] float NULL ,
[pps_f] float NULL ,
[pps_b] float NULL ,
[score] float NULL ,
[rec_time] datetime NULL
)
