//vier_paper_para_abnormal

SELECT
a.reel_code AS [轴号],
b.ProductName AS [品种],
c.Machine_Name AS [机台],
convert(varchar,a.rec_date,112) AS [日期],
a.oper_id AS [检验员],
a.temperature AS [室内温度],
a.humidity AS [相对湿度],
a.director_name AS [主管],
a.remark AS [备注],
a.sur_oil_imbibition_f AS [表面吸油性正],
a.sur_oil_imbibition_b AS [表面吸油性反],
a.water_imbibition_f AS [吸水性正],
a.water_imbibition_b AS [吸水性反],
a.sur_Strength_v_f AS [表面强度-纵-正],
a.sur_Strength_v_b AS [表面强度-纵-反],
a.sur_Strength_h_f AS [表面强度-横-正],
a.sur_Strength_h_b AS [表面强度-横-反],
a.oil_perme_f AS [油渗性正],
a.oil_perme_f_lv AS [油渗性正-等级],
a.oil_perme_b AS [油渗性反],
a.oil_perme_b_lv AS [油渗性反-等级],
a.roughness_v_f AS [粗糙度-纵-正],
a.roughness_v_b AS [粗糙度-纵-反],
a.roughness_h_f AS [粗糙度-横-正],
a.roughness_h_b AS [粗糙度-横-反],
a.perme_v_f AS [渗透性-纵-正],
a.perme_v_b AS [渗透性-纵-反],
a.perme_h_f AS [渗透性-横-正],
a.perme_h_b AS [渗透性-横-反],
a.burst_f AS [耐破度正],
a.burst_b AS [耐破度反],
a.evennessIdx_f AS [匀度指数正],
a.evennessIdx_b AS [匀度指数反],
a.pps_f AS [PPS正],
a.pps_b AS [PPS反],
a.score AS [得分],
a.rec_time AS [录入时间]

FROM
Paper_Para_Abnormal AS a INNER JOIN Paper_ProductData b on a.prod_id = b.ProductID INNER JOIN Paper_Machine_Info c on a.machine_id = c.Machine_ID